### ISSUE TITLE
Nova 5.0 Support?

### ISSUE THREAD

**Issue by smartens80** [Muetze42/nova-assets-versioning#2]
Can we get Nova 5.0 support?

**Comment by Muetze42** [comment]
Yes. Definitely. My Laravel installer also installs it...

https://github.com/Muetze42/nova-assets-versioning/releases

**Comment by smartens80** [comment]
> Yes. Definitely. My Laravel installer also installs it...
> 
> https://github.com/Muetze42/nova-assets-versioning/releases

Thanks for that, I can confirm v1.1.0 is working as expected with Nova 5.0
